In [2]:
import torch

### Tensors

unintialized matrix

In [11]:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  1.0842e-19, -1.1108e+10],
        [ 1.0845e-19,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.0842e-19, -1.1096e+10]])


random initialized matrix

In [12]:
x = torch.rand(5,3)
print(x)

tensor([[0.4164, 0.4523, 0.9839],
        [0.8670, 0.3110, 0.2175],
        [0.9883, 0.0701, 0.4428],
        [0.3227, 0.1313, 0.1732],
        [0.3073, 0.1655, 0.2770]])


matrix filled with zeros, dtype = torch.long is int64

In [15]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


tensor directly from data

In [17]:
x = torch.tensor([5,3])
print(x)

tensor([5, 3])


construct matrix from existing matrix

In [20]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.rand_like(x)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.2445, 0.9282, 0.7113],
        [0.1231, 0.4000, 0.3694],
        [0.4113, 0.6601, 0.2316],
        [0.8751, 0.4491, 0.4188],
        [0.1097, 0.1197, 0.3218]], dtype=torch.float64)


In [24]:
print(x.size())

torch.Size([5, 3])


### Operations

adding

In [31]:
y = torch.rand(5,3, dtype=torch.double)
print(x + y)
print(torch.add(x,y))

tensor([[0.8908, 1.6320, 1.6813],
        [0.8260, 0.7619, 0.6588],
        [1.2683, 0.8216, 0.5251],
        [1.3948, 1.2360, 0.6288],
        [0.5313, 0.1675, 1.2282]], dtype=torch.float64)
tensor([[0.8908, 1.6320, 1.6813],
        [0.8260, 0.7619, 0.6588],
        [1.2683, 0.8216, 0.5251],
        [1.3948, 1.2360, 0.6288],
        [0.5313, 0.1675, 1.2282]], dtype=torch.float64)


assign result

In [33]:
result = torch.empty(5,3, dtype=torch.double)
torch.add(x,y,out=result)
print(result)

tensor([[0.8908, 1.6320, 1.6813],
        [0.8260, 0.7619, 0.6588],
        [1.2683, 0.8216, 0.5251],
        [1.3948, 1.2360, 0.6288],
        [0.5313, 0.1675, 1.2282]], dtype=torch.float64)

tensor([[0.8908, 1.6320, 1.6813],
        [0.8260, 0.7619, 0.6588],
        [1.2683, 0.8216, 0.5251],
        [1.3948, 1.2360, 0.6288],
        [0.5313, 0.1675, 1.2282]], dtype=torch.float64)


inplace adding

In [34]:
y.add_(x)

tensor([[0.8908, 1.6320, 1.6813],
        [0.8260, 0.7619, 0.6588],
        [1.2683, 0.8216, 0.5251],
        [1.3948, 1.2360, 0.6288],
        [0.5313, 0.1675, 1.2282]], dtype=torch.float64)

indexing, same as numpy

In [37]:
print(x[:,1])

tensor([0.9282, 0.4000, 0.6601, 0.4491, 0.1197], dtype=torch.float64)


resize

In [41]:
x = torch.randn(4,4)
print(x)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

tensor([[ 0.0757,  0.1377,  1.8439, -0.1051],
        [-0.0129, -0.9529, -1.1263,  0.2056],
        [ 0.9963,  0.6694,  0.7337, -1.7639],
        [ 0.4418, -0.7200,  0.7474, -0.3071]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


get value

In [42]:
x = torch.rand(1)
print(x)
x.item()

tensor([0.4186])


0.41857367753982544

### Numpy bridge

from tensor to np, they share memory

In [44]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [46]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [47]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


from np to tensor

In [48]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [50]:
np.add(a,1, out = a)
print(a)
print(b)

array([2., 2., 2., 2., 2.])

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensor

In [51]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    